verifyDepsBeforeRun: install

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - eslint-config-prettier@9.1.2

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
- nuxt
